-- MySQL Script generated by MySQL Workbench
-- qua 25 ago 2021 22:18:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify` ;
USE `spotify` ;

-- -----------------------------------------------------
-- Table `spotify`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`USUARIO` (
  `IDUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOMEUSUARIO` VARCHAR(45) NULL,
  `DATA_NAC` DATE NULL,
  `SEXO` VARCHAR(1) NULL,
  `EMAIL` VARCHAR(150) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDUSUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`PLAYLIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`PLAYLIST` (
  `IDPLAYLIST` INT NOT NULL AUTO_INCREMENT,
  `IDUSUARIO` INT NULL,
  `TITULO` VARCHAR(45) NULL,
  `QTDCANCOES` INT NULL,
  `DATACRIACAO` DATE NULL,
  PRIMARY KEY (`IDPLAYLIST`),
  INDEX `FK_PLAYLIST_USUARIO_idx` (`IDUSUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_PLAYLIST_USUARIO`
    FOREIGN KEY (`IDUSUARIO`)
    REFERENCES `spotify`.`USUARIO` (`IDUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`ARTISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`ARTISTA` (
  `IDARTISTA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `SOBRENOME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IDARTISTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`ALBUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`ALBUM` (
  `IDALBUM` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `IDARTISTA` INT NOT NULL,
  PRIMARY KEY (`IDALBUM`),
  INDEX `FK_ALBUM_ARTISTA_idx` (`IDARTISTA` ASC) VISIBLE,
  CONSTRAINT `FK_ALBUM_ARTISTA`
    FOREIGN KEY (`IDARTISTA`)
    REFERENCES `spotify`.`ARTISTA` (`IDARTISTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`CANCOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`CANCOES` (
  `IDCANCAO` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `DURACAO` DOUBLE NULL,
  `QTDREPRODUCAO` INT NULL,
  `QTDLIKES` INT NULL,
  `IDALBUM` INT NULL,
  PRIMARY KEY (`IDCANCAO`),
  INDEX `FK_CANCAO_ALBUM_idx` (`IDALBUM` ASC) VISIBLE,
  CONSTRAINT `FK_CANCAO_ALBUM`
    FOREIGN KEY (`IDALBUM`)
    REFERENCES `spotify`.`ALBUM` (`IDALBUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`PLAYLIST_CANCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`PLAYLIST_CANCAO` (
  `IDPLAYLIST_CANCAO` INT NOT NULL AUTO_INCREMENT,
  `IDCANCAO` INT NOT NULL,
  `IDPLAYLIST` INT NOT NULL,
  PRIMARY KEY (`IDPLAYLIST_CANCAO`),
  INDEX `FK_PLAY_CANC_CANCAO_idx` (`IDCANCAO` ASC) VISIBLE,
  INDEX `FK_PLAY_CANC_PLAYLIST_idx` (`IDPLAYLIST` ASC) VISIBLE,
  CONSTRAINT `FK_PLAY_CANC_CANCAO`
    FOREIGN KEY (`IDCANCAO`)
    REFERENCES `spotify`.`CANCOES` (`IDCANCAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLAY_CANC_PLAYLIST`
    FOREIGN KEY (`IDPLAYLIST`)
    REFERENCES `spotify`.`PLAYLIST` (`IDPLAYLIST`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`GENERO` (
  `IDGENERO` INT NOT NULL AUTO_INCREMENT,
  `GENERO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDGENERO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`GENEROCANCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`GENEROCANCAO` (
  `IDGENEROCANCAO` INT NOT NULL AUTO_INCREMENT,
  `IDCANCAO` INT NOT NULL,
  `IDGENERO` INT NOT NULL,
  PRIMARY KEY (`IDGENEROCANCAO`),
  INDEX `FK_GENER_CANC_CANCAO_idx` (`IDCANCAO` ASC) VISIBLE,
  INDEX `FK_GENER_CANC_GENERO_idx` (`IDGENERO` ASC) VISIBLE,
  CONSTRAINT `FK_GENER_CANC_CANCAO`
    FOREIGN KEY (`IDCANCAO`)
    REFERENCES `spotify`.`CANCOES` (`IDCANCAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GENER_CANC_GENERO`
    FOREIGN KEY (`IDGENERO`)
    REFERENCES `spotify`.`GENERO` (`IDGENERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;